#!/usr/bin/env bash
# ============================================================
#  Barzin Tunnel Infrastructure Setup Script
#  Updated: 2026-03-14  — MasterDnsVPN replaces NoizDNS/dnstt
# ============================================================
#
#  Modes:
#    install           — Full Frankfurt server setup
#                         (MasterDnsVPN + Slipstream + dnstm)
#    masterdnsvpn      — Install / reinstall MasterDnsVPN only
#    masterdnsvpn-migrate — Migrate from NoizDNS/dnstt to MasterDnsVPN
#    slipstream        — Set up Slipstream only
#    status            — Show current tunnel service status
#    middle-proxy      — Iranian VPS: dnsmasq DNS multiplexer
#
#  Architecture (Frankfurt server 138.124.115.113):
#    dnstm router → UDP :53
#      ├─ a.barzin.biz  → forward  → MasterDnsVPN  :5312 (SOCKS5 built-in)
#      └─ b.barzin.biz  → slipstream→ microsocks   :58077 (public SOCKS5)
#
#  MasterDnsVPN details:
#    Binary  : /opt/masterdnsvpn/MasterDnsVPN_Server
#    Config  : /opt/masterdnsvpn/server_config.toml
#    Key     : /opt/masterdnsvpn/encrypt_key.txt
#    Service : masterdnsvpn.service
#    Port    : UDP 5312 (behind dnstm, never exposed directly)
#    Domain  : a.barzin.biz
#    Encryption: ChaCha20 (method 2)
#    Protocol  : SOCKS5 (built-in, no external microsocks needed)
#
#  Slipstream details (unchanged):
#    Domain  : b.barzin.biz
#    Port    : 5310 (behind dnstm)
#    Backend : microsocks on :58077 (user: barzin / FFbCXFUlIwmjOBG!I5)
#
#  NoizDNS / dnstt:  *** DEPRECATED — replaced by MasterDnsVPN ***
#    Old domain: a.barzin.biz (same NS delegation reused)
#    Old port  : 5311
# ============================================================

set -euo pipefail

# ─── Config ─────────────────────────────────────────────────
SERVER_IP="138.124.115.113"
MDNS_DOMAIN="a.barzin.biz"          # MasterDnsVPN domain (reuses NoizDNS NS delegation)
SLIP_DOMAIN="b.barzin.biz"          # Slipstream domain (unchanged)

MDNS_INSTALL_DIR="/opt/masterdnsvpn"
MDNS_PORT="5312"                    # Internal port behind dnstm forward transport
MDNS_ENCRYPTION="2"                 # 2=ChaCha20 (fast + secure)
MDNS_PROTOCOL="SOCKS5"              # Built-in SOCKS5 (no microsocks needed)

SOCKS_USER="barzin"
SOCKS_PASS="FFbCXFUlIwmjOBG\!I5"
SOCKS_PORT="58076"
PUB_SOCKS_PORT="58077"
DNSTT_PORT="5311"                   # Legacy NoizDNS port (will be stopped)

CF_EMAIL="Aminkhodayari98.ak@gmail.com"
CF_API_KEY="746c7c8e961788a2d97b27e59480832514be1"
CF_ZONE_ID="925bc52d84999ca3707b716a8811a84c"

# GitHub release base URL
MDNS_GH_BASE="https://github.com/masterking32/MasterDnsVPN/releases/latest/download"

# ─── Helpers ────────────────────────────────────────────────
info()    { echo -e "\e[32m[+]\e[0m $*"; }
warn()    { echo -e "\e[33m[!]\e[0m $*"; }
error()   { echo -e "\e[31m[-]\e[0m $*"; exit 1; }
section() { echo -e "\n\e[36m━━━ $* ━━━\e[0m"; }
hr()      { echo "────────────────────────────────────────────"; }

require() { command -v "$1" >/dev/null 2>&1 || error "Missing command: $1. Install it first."; }

# ─── 1. Download MasterDnsVPN server binary ─────────────────
download_masterdnsvpn() {
    section "Downloading MasterDnsVPN Server"

    # Detect arch
    local arch
    arch=$(uname -m)
    local asset
    case "$arch" in
        x86_64)  asset="MasterDnsVPN_Server_Linux_AMD64.tar.gz" ;;
        aarch64) asset="MasterDnsVPN_Server_Linux_ARM64.tar.gz" ;;
        *)        error "Unsupported architecture: $arch" ;;
    esac

    # Try modern glibc first, fall back to legacy
    local url="${MDNS_GH_BASE}/${asset}"
    local url_legacy="${MDNS_GH_BASE}/${asset/Linux/Linux-Legacy}"

    mkdir -p "$MDNS_INSTALL_DIR"
    local tmp; tmp=$(mktemp -d)

    info "Downloading ${asset}..."
    if ! wget -q "$url" -O "${tmp}/server.tar.gz"; then
        warn "Modern glibc build failed — trying legacy build..."
        wget -q "$url_legacy" -O "${tmp}/server.tar.gz" || error "Download failed"
        asset="${asset/Linux/Linux-Legacy}"
    fi

    tar xf "${tmp}/server.tar.gz" -C "${tmp}"
    local bin; bin=$(find "${tmp}" -type f -name 'MasterDnsVPN_Server*' | head -1)
    [[ -z "$bin" ]] && error "Could not find server binary in archive"

    mv "$bin" "${MDNS_INSTALL_DIR}/MasterDnsVPN_Server"
    chmod +x "${MDNS_INSTALL_DIR}/MasterDnsVPN_Server"
    rm -rf "$tmp"

    local ver; ver=$("${MDNS_INSTALL_DIR}/MasterDnsVPN_Server" --version 2>/dev/null || echo "unknown")
    info "Installed: ${ver}"
}

# ─── 2. Generate server config ───────────────────────────────
write_server_config() {
    section "Writing server_config.toml"

    # Generate or reuse encrypt key
    local key_file="${MDNS_INSTALL_DIR}/encrypt_key.txt"
    local enc_key
    if [[ -f "$key_file" ]]; then
        enc_key=$(cat "$key_file")
        info "Reusing existing encrypt key."
    else
        # MasterDnsVPN expects a key generated by the server — start it briefly to generate
        # OR use a strong random hex string (32 bytes = 64 hex chars)
        enc_key=$(openssl rand -hex 32)
        echo "$enc_key" > "$key_file"
        chmod 600 "$key_file"
        info "Generated new encrypt key → ${key_file}"
    fi

    cat > "${MDNS_INSTALL_DIR}/server_config.toml" << TOML
# ==============================================================================
# MasterDnsVPN Server Config — barzin.biz
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ==============================================================================

# ── DNS Listener ──────────────────────────────────────────────────────────────
# Runs on port ${MDNS_PORT} (behind dnstm forward transport; not exposed on :53)
UDP_HOST = "127.0.0.1"
UDP_PORT = ${MDNS_PORT}

# Domain for this tunnel (must match client DOMAINS setting)
DOMAIN = ["${MDNS_DOMAIN}"]

# ── Protocol ──────────────────────────────────────────────────────────────────
# SOCKS5 mode: server handles SOCKS5 internally — no external proxy needed
PROTOCOL_TYPE = "${MDNS_PROTOCOL}"
USE_EXTERNAL_SOCKS5 = false
FORWARD_IP = "127.0.0.1"
FORWARD_PORT = 1080
SOCKS5_AUTH = false
SOCKS5_USER = "admin"
SOCKS5_PASS = "123456"
SOCKS_HANDSHAKE_TIMEOUT = 120.0

# ── Encryption ────────────────────────────────────────────────────────────────
# 0=None 1=XOR 2=ChaCha20 3=AES-128-GCM 4=AES-192-GCM 5=AES-256-GCM
DATA_ENCRYPTION_METHOD = ${MDNS_ENCRYPTION}

# Compression (0=OFF 1=ZSTD 2=LZ4 3=ZLIB)
SUPPORTED_UPLOAD_COMPRESSION_TYPES   = [0, 1, 2, 3]
SUPPORTED_DOWNLOAD_COMPRESSION_TYPES = [0, 1, 2, 3]

# ── ARQ / Reliability ─────────────────────────────────────────────────────────
# Tuned for high-packet-loss networks (Iran ISP conditions)
ARQ_WINDOW_SIZE        = 256
ARQ_INITIAL_RTO        = 0.4
ARQ_MAX_RTO            = 1.2
ARQ_CONTROL_INITIAL_RTO = 0.4
ARQ_CONTROL_MAX_RTO     = 1.2
ARQ_CONTROL_MAX_RETRIES = 200

# ── Session ───────────────────────────────────────────────────────────────────
SESSION_TIMEOUT          = 300
SESSION_CLEANUP_INTERVAL = 30
MAX_SESSIONS             = 255

# ── Performance ───────────────────────────────────────────────────────────────
MAX_CONCURRENT_REQUESTS = 500
CPU_WORKER_THREADS      = 0
MAX_PACKETS_PER_BATCH   = 1000
SOCKET_BUFFER_SIZE      = 8388608

LOG_LEVEL      = "INFO"
CONFIG_VERSION = 3.0
TOML

    info "Config written → ${MDNS_INSTALL_DIR}/server_config.toml"
    info "Encrypt key  → ${key_file}"
}

# ─── 3. Systemd service ──────────────────────────────────────
install_systemd_service() {
    section "Installing masterdnsvpn.service"

    cat > /etc/systemd/system/masterdnsvpn.service << UNIT
[Unit]
Description=MasterDnsVPN Server — ${MDNS_DOMAIN}
Documentation=https://github.com/masterking32/MasterDnsVPN
After=network-online.target dnstm-dnsrouter.service
Wants=network-online.target
BindsTo=dnstm-dnsrouter.service

[Service]
Type=simple
User=root
WorkingDirectory=${MDNS_INSTALL_DIR}
ExecStart=${MDNS_INSTALL_DIR}/MasterDnsVPN_Server
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
LimitNOFILE=65536

# Security
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes
ReadWritePaths=${MDNS_INSTALL_DIR}
ProtectKernelTunables=yes
ProtectControlGroups=yes

[Install]
WantedBy=multi-user.target
UNIT

    systemctl daemon-reload
    info "masterdnsvpn.service installed"
}

# ─── 4. Update dnstm config ──────────────────────────────────
update_dnstm_config() {
    section "Updating dnstm config (a.barzin.biz → forward → MasterDnsVPN)"

    local cfg="/etc/dnstm/config.json"
    [[ -f "$cfg" ]] || error "dnstm config not found: $cfg"

    # Backup
    cp "$cfg" "${cfg}.bak-$(date +%Y%m%d%H%M%S)"

    # Build new config: replace dnstt tunnel with forward transport to MasterDnsVPN
    python3 - << PYEOF
import json, sys

with open('$cfg') as f:
    c = json.load(f)

# Remove dnstt-socks tunnel and socks-noauth backend (NoizDNS legacy)
c['tunnels'] = [t for t in c.get('tunnels', []) if t.get('transport') != 'dnstt']
c['backends'] = [b for b in c.get('backends', []) if b.get('tag') != 'socks-noauth']

# Add MasterDnsVPN forward tunnel (if not already present)
tags = {t['tag'] for t in c.get('tunnels', [])}
if 'mdns-forward' not in tags:
    c['tunnels'].append({
        "tag": "mdns-forward",
        "enabled": True,
        "transport": "forward",
        "domain": "${MDNS_DOMAIN}",
        "port": int("${MDNS_PORT}"),
        "forward": {
            "address": "127.0.0.1:${MDNS_PORT}"
        }
    })

# Set route default to slip-socks (Slipstream) — keep Slipstream as primary
c['route'] = {
    "mode": "multi",
    "active": "slip-socks",
    "default": "slip-socks"
}

with open('$cfg', 'w') as f:
    json.dump(c, f, indent=2)
print("dnstm config updated")
PYEOF

    info "dnstm config updated → removed dnstt, added mdns-forward tunnel"
}

# ─── 5. Stop legacy NoizDNS services ─────────────────────────
stop_legacy_services() {
    section "Stopping legacy NoizDNS / dnstt services"

    for svc in dnstm-dnstt-ssh microsocks-noauth; do
        if systemctl is-active --quiet "$svc" 2>/dev/null; then
            info "Stopping ${svc}..."
            systemctl stop "$svc" || warn "Could not stop ${svc}"
        fi
        if systemctl is-enabled --quiet "$svc" 2>/dev/null; then
            info "Disabling ${svc}..."
            systemctl disable "$svc" || warn "Could not disable ${svc}"
        fi
    done

    info "Legacy services stopped and disabled."
}

# ─── 6. Start / restart everything ───────────────────────────
start_services() {
    section "Starting services"

    # Restart dnstm router first (picks up new config)
    info "Restarting dnstm-dnsrouter..."
    systemctl restart dnstm-dnsrouter || warn "dnstm-dnsrouter restart failed"

    # Start MasterDnsVPN
    info "Enabling & starting masterdnsvpn..."
    systemctl enable --now masterdnsvpn

    # Verify
    sleep 3
    if systemctl is-active --quiet masterdnsvpn; then
        info "masterdnsvpn  ✓ running"
    else
        warn "masterdnsvpn not running — check: journalctl -u masterdnsvpn -n 30"
    fi
    if systemctl is-active --quiet dnstm-dnsrouter; then
        info "dnstm-dnsrouter ✓ running"
    else
        warn "dnstm-dnsrouter not running — check: journalctl -u dnstm-dnsrouter -n 30"
    fi
}

# ─── 7. Print client config ──────────────────────────────────
print_client_config() {
    section "Client Configuration"

    local key_file="${MDNS_INSTALL_DIR}/encrypt_key.txt"
    local enc_key; enc_key=$(cat "$key_file" 2>/dev/null || echo "CHECK ${key_file}")

    hr
    echo ""
    echo "  MasterDnsVPN CLIENT CONFIG"
    echo "  ─────────────────────────"
    echo "  Binary : MasterDnsVPN_Client_*  (download from GitHub releases)"
    echo "  GitHub : https://github.com/masterking32/MasterDnsVPN/releases/latest"
    echo ""
    echo "  ── client_config.toml ──────────────────────────────────────────"
    cat << CLIENTCFG

# SOCKS5 proxy listen address (your local machine)
SOCKS5_HOST = "127.0.0.1"
SOCKS5_PORT = 1080

# Tunnel domain
DOMAINS = ["${MDNS_DOMAIN}"]

# Must match server DATA_ENCRYPTION_METHOD (2=ChaCha20)
DATA_ENCRYPTION_METHOD = ${MDNS_ENCRYPTION}

# Encryption key — get from server: cat ${MDNS_INSTALL_DIR}/encrypt_key.txt
ENCRYPT_KEY = "${enc_key}"

# DNS resolvers for tunnel traffic
# Add more for load balancing / redundancy
RESOLVERS_FILE = "client_resolvers.txt"

# ARQ settings (match server)
ARQ_WINDOW_SIZE  = 256
ARQ_INITIAL_RTO  = 0.4
ARQ_MAX_RTO      = 1.2

PROTOCOL_TYPE = "SOCKS5"
LOG_LEVEL     = "INFO"

CLIENTCFG
    echo "  ─────────────────────────────────────────────────────────────────"
    echo ""
    echo "  IMPORTANT: Run the client auto-scan first to find optimal resolvers:"
    echo "    ./MasterDnsVPN_Client --scan"
    echo ""
    echo "  Then start the tunnel:"
    echo "    ./MasterDnsVPN_Client"
    echo ""
    echo "  Configure your device to use SOCKS5:"
    echo "    Host: 127.0.0.1  Port: 1080"
    echo ""
    hr
}

# ─── Status ──────────────────────────────────────────────────
show_status() {
    section "Tunnel Infrastructure Status"
    local services=(masterdnsvpn dnstm-dnsrouter dnstm-slip-socks microsocks-slip-public microsocks)
    for svc in "${services[@]}"; do
        local state="stopped"
        systemctl is-active --quiet "$svc" 2>/dev/null && state="running"
        printf "  %-35s  %s\n" "$svc" "$([ "$state" = running ] && echo -e "\e[32m● running\e[0m" || echo -e "\e[31m○ stopped\e[0m")"
    done
    echo ""
    # Legacy services (should be stopped)
    local legacy=(dnstm-dnstt-ssh microsocks-noauth)
    for svc in "${legacy[@]}"; do
        local state="stopped"
        systemctl is-active --quiet "$svc" 2>/dev/null && state="running"
        if [[ "$state" == "running" ]]; then
            printf "  %-35s  \e[33m⚠ still running (legacy — should be stopped)\e[0m\n" "$svc"
        fi
    done
    echo ""
    # Port check
    info "Port 53 listener:"
    ss -lnup sport = :53 2>/dev/null | head -3 || true
    info "Port ${MDNS_PORT} listener (MasterDnsVPN internal):"
    ss -lnup sport = :"${MDNS_PORT}" 2>/dev/null | head -3 || true
}

# ─── Middle proxy (Iranian VPS) ───────────────────────────────
setup_middle_proxy() {
    section "Setting up middle-proxy (dnsmasq DNS multiplexer)"
    require dnsmasq

    info "Configuring dnsmasq to forward *.barzin.biz → ${SERVER_IP}..."
    cat > /etc/dnsmasq.d/barzin-tunnel.conf << DNSCONF
server=/a.barzin.biz/8.8.8.8
server=/a.barzin.biz/1.1.1.1
server=/a.barzin.biz/9.9.9.9
server=/a.barzin.biz/8.8.4.4
server=/a.barzin.biz/1.0.0.1
server=/a.barzin.biz/208.67.222.222
server=/b.barzin.biz/8.8.8.8
server=/b.barzin.biz/1.1.1.1
server=/b.barzin.biz/9.9.9.9
DNSCONF

    systemctl restart dnsmasq
    info "dnsmasq middle-proxy configured."
    info "Point SlipNet DNS to this VPS IP."
}

# ─── Full install ─────────────────────────────────────────────
install_full() {
    section "Full install: MasterDnsVPN + Slipstream + dnstm"
    install_deps
    download_masterdnsvpn
    write_server_config
    install_systemd_service
    stop_legacy_services
    update_dnstm_config
    start_services
    print_client_config
}

# ─── MasterDnsVPN only ────────────────────────────────────────
install_masterdnsvpn_only() {
    section "Installing MasterDnsVPN"
    install_deps
    download_masterdnsvpn
    write_server_config
    install_systemd_service
    stop_legacy_services
    update_dnstm_config
    start_services
    print_client_config
}

# ─── Migrate from NoizDNS ─────────────────────────────────────
migrate_from_noizdns() {
    section "Migrating from NoizDNS/dnstt → MasterDnsVPN"

    warn "This will:"
    warn "  1. Stop dnstm-dnstt-ssh (NoizDNS) permanently"
    warn "  2. Stop microsocks-noauth"
    warn "  3. Install MasterDnsVPN on ${MDNS_DOMAIN} port ${MDNS_PORT}"
    warn "  4. Update dnstm to use 'forward' transport for ${MDNS_DOMAIN}"
    echo ""
    read -r -p "Continue? [y/N] " confirm
    [[ "${confirm,,}" == "y" ]] || { info "Aborted."; exit 0; }

    install_deps
    download_masterdnsvpn
    write_server_config
    install_systemd_service
    stop_legacy_services
    update_dnstm_config
    start_services
    print_client_config

    info "Migration complete. NoizDNS/dnstt has been replaced by MasterDnsVPN."
    info "Update SlipNet client profiles: change NoizDNS domain to ${MDNS_DOMAIN}"
    info "  Encryption key: cat ${MDNS_INSTALL_DIR}/encrypt_key.txt"
}

# ─── Update MasterDnsVPN ──────────────────────────────────────
update_masterdnsvpn() {
    section "Updating MasterDnsVPN to latest release"
    systemctl stop masterdnsvpn 2>/dev/null || true
    download_masterdnsvpn
    systemctl start masterdnsvpn
    info "MasterDnsVPN updated and restarted."
    journalctl -u masterdnsvpn -n 5 --no-pager
}

# ─── Deps ─────────────────────────────────────────────────────
install_deps() {
    info "Installing dependencies..."
    apt-get update -qq
    apt-get install -y curl wget unzip python3 openssl 2>/dev/null || true
}

# ─── Main ─────────────────────────────────────────────────────
MODE="${1:-help}"

case "$MODE" in
    install)             install_full ;;
    masterdnsvpn)        install_masterdnsvpn_only ;;
    masterdnsvpn-migrate)migrate_from_noizdns ;;
    masterdnsvpn-update) update_masterdnsvpn ;;
    status)              show_status ;;
    middle-proxy)        setup_middle_proxy ;;
    client-config)       print_client_config ;;
    *)
        echo ""
        echo "  Barzin Tunnel Infrastructure Setup"
        echo ""
        echo "  Usage:  $0 <mode>"
        echo ""
        echo "  Modes:"
        echo "    install               Full setup (MasterDnsVPN + Slipstream + dnstm)"
        echo "    masterdnsvpn          Install MasterDnsVPN only (+ update dnstm config)"
        echo "    masterdnsvpn-migrate  Migrate from NoizDNS/dnstt → MasterDnsVPN"
        echo "    masterdnsvpn-update   Update MasterDnsVPN binary to latest release"
        echo "    status                Show all tunnel service status"
        echo "    middle-proxy          Set up Iranian VPS DNS multiplexer (dnsmasq)"
        echo "    client-config         Print client config for MasterDnsVPN"
        echo ""
        echo "  Tunnel domains:"
        echo "    a.barzin.biz → MasterDnsVPN (DNS tunnel, built-in SOCKS5)"
        echo "    b.barzin.biz → Slipstream   (DNS tunnel, SOCKS5 via microsocks)"
        echo ""
        ;;
esac
